"""
Research graph skeleton (Step 6A) + plan/search wiring (Step 6B)
+ process/cleanup wiring (Step 6C).

Builds a LangGraph `StateGraph` wiring together the research pipeline's
nodes in sequence:

    START -> analyze -> plan -> search -> process -> summarize
          -> validate -> quality_check -> report -> END

Step 6B connects two nodes to real logic:
  - `plan`   -> calls the existing `QueryPlanner` to build a `ResearchPlan`.
  - `search` -> calls the existing `TavilySearchService` for each query in
               that plan.

Step 6C connects a third node:
  - `process` -> cleans and deduplicates the raw `search_results` gathered
               by `search`: drops invalid/empty entries and duplicate
               URLs, and otherwise preserves valid `SearchResult` data
               unchanged.

Step 6D connects a fourth node:
  - `summarize` -> calls the existing `Summarizer` to synthesize cleaned
               `search_results` into structured `Finding` objects, using
               `LLMManager` under the hood. Purely factual synthesis with
               attached source URLs — no validation pass, no retries.

Step 6E connects a fifth node:
  - `validate` -> re-validates each `Finding` against the existing Pydantic
               schema plus a minimal business rule (must cite at least
               one source). Findings that pass become
               `validated_findings`; rejected findings are never modified
               or fabricated — they're simply left out, with a message
               recorded in `errors` explaining why.

Step 6F connects a sixth node:
  - `quality_check` -> decides whether `validated_findings` are sufficient
               to proceed to `report`. If not, and the retry limit hasn't
               been reached, it increments `retry_count` and routes the
               graph back to `plan` for another research attempt. Once
               `MAX_RETRY_COUNT` retries have been used (a safe cap), it
               proceeds to `report` regardless, recording why. Uses
               LangGraph's `Command` to make the state update and the
               routing decision atomically in one place.

Step 6G connects a seventh node:
  - `report` -> calls the existing `ReportGenerator` to assemble a fully
               validated `ResearchReport` from `validated_findings`,
               using `LLMManager` under the hood. The LLM only writes the
               narrative (title, executive summary, key findings) — the
               `findings` and `sources` fields are built directly from
               the already-validated data, never regenerated by the LLM.

`analyze` remains an unimplemented placeholder pass-through. No UI or
FastAPI wiring lives here yet.
"""

from __future__ import annotations

import logging

from langgraph.graph import END, START, StateGraph
from langgraph.graph.state import CompiledStateGraph
from langgraph.types import Command
from pydantic import ValidationError

from app.agents.query_planner import QueryPlanner, QueryPlannerError
from app.agents.report_generator import ReportGenerator, ReportGeneratorError
from app.agents.summarizer import Summarizer, SummarizerError
from app.graph.state import ResearchState
from app.schemas.models import Finding, SearchResult
from app.services.tavily_service import TavilyServiceError, TavilySearchService

logger = logging.getLogger("app.research_graph")


# ---------------------------------------------------------------------------
# Placeholder nodes (unimplemented, unchanged from Step 6A)
# ---------------------------------------------------------------------------
#
# Each node receives the full `ResearchState` and returns a (possibly
# partial) state update. These remaining nodes are still no-op
# pass-throughs. Real logic is added in later steps.


def analyze_node(state: ResearchState) -> ResearchState:
    """Placeholder: will analyze the user's prompt/intent."""
    logger.info("Node 'analyze' executed (placeholder pass-through).")
    return state


def process_node(state: ResearchState) -> ResearchState:
    """
    Clean and deduplicate `search_results`.

    - Ignores entries that aren't valid `SearchResult` instances, or that
      have an empty/whitespace-only title, content, or URL.
    - Removes duplicate URLs (normalized: trimmed, trailing slash removed,
      lowercased), keeping the first occurrence and its original data.
    - Preserves all other valid `SearchResult` data untouched.
    - Does not call any LLM, does not summarize, does not retry.
    """
    logger.info("Node 'process' executing: cleaning and deduplicating search_results.")
    errors = list(state.get("errors", []))
    raw_results = state.get("search_results") or []

    seen_urls: set[str] = set()
    cleaned: list[SearchResult] = []
    skipped_invalid = 0
    skipped_duplicate = 0

    for result in raw_results:
        if not isinstance(result, SearchResult):
            skipped_invalid += 1
            continue

        if not result.title or not result.title.strip():
            skipped_invalid += 1
            continue

        if not result.content or not result.content.strip():
            skipped_invalid += 1
            continue

        url_key = str(result.url).strip().rstrip("/").lower()
        if not url_key:
            skipped_invalid += 1
            continue

        if url_key in seen_urls:
            skipped_duplicate += 1
            continue

        seen_urls.add(url_key)
        cleaned.append(result)

    logger.info(
        "Node 'process': %d input result(s) -> %d cleaned result(s) "
        "(%d invalid/empty skipped, %d duplicate skipped).",
        len(raw_results),
        len(cleaned),
        skipped_invalid,
        skipped_duplicate,
    )

    return {"search_results": cleaned, "errors": errors}


def validate_node(state: ResearchState) -> ResearchState:
    """
    Validate `findings` against the existing `Finding` schema plus a
    minimal business rule (a finding must cite at least one source).

    - Any item that isn't actually a `Finding` instance is rejected.
    - Each `Finding` is re-validated through the Pydantic schema itself
      (`Finding.model_validate`) to catch any drift/corruption.
    - Any `Finding` with an empty `sources` list is rejected (an
      unsourced "finding" isn't something this pipeline should report).
    - Findings that pass become `validated_findings`, unmodified.
    - Rejected findings are never fabricated or altered — they're simply
      left out, with a message recorded in `errors` explaining why.
    - Does not retry, does not run the quality-check step, does not
      assemble a report.
    """
    logger.info("Node 'validate' executing: validating findings against the Finding schema.")
    errors = list(state.get("errors", []))
    findings = state.get("findings") or []

    validated: list[Finding] = []
    rejected_count = 0

    for finding in findings:
        if not isinstance(finding, Finding):
            errors.append(
                f"validate: rejected a non-Finding item ({type(finding).__name__})."
            )
            rejected_count += 1
            continue

        try:
            Finding.model_validate(finding.model_dump())
        except ValidationError as exc:
            errors.append(
                f"validate: rejected finding {finding.topic!r} (schema error: {exc})."
            )
            rejected_count += 1
            continue

        if not finding.sources:
            errors.append(
                f"validate: rejected finding {finding.topic!r} (no sources cited)."
            )
            rejected_count += 1
            continue

        validated.append(finding)

    logger.info(
        "Node 'validate': %d input finding(s) -> %d validated, %d rejected.",
        len(findings),
        len(validated),
        rejected_count,
    )

    return {"validated_findings": validated, "errors": errors}


MAX_RETRY_COUNT = 2  # Safe cap: at most 2 retries back to `plan` before proceeding to `report` regardless.


def quality_check_node(state: ResearchState) -> Command:
    """
    Decide whether `validated_findings` are sufficient to proceed to
    `report`, or whether the graph should loop back to `plan` for another
    research attempt.

    Sufficiency is a minimal, explicit gate: at least one validated
    finding. If insufficient and the retry limit has not been reached,
    `retry_count` is incremented and the graph routes back to `plan`.
    Once `MAX_RETRY_COUNT` retries have been used, it proceeds to
    `report` anyway with whatever was found, recording why.

    Returns a `Command` so the state update and the routing decision are
    made atomically, in one place, based on the exact `retry_count` this
    invocation saw — this avoids any ambiguity that could arise from
    trying to re-derive the routing decision from `retry_count` alone
    after the fact.
    """
    logger.info("Node 'quality_check' executing.")
    errors = list(state.get("errors", []))
    validated = state.get("validated_findings") or []
    retry_count = state.get("retry_count", 0)

    if len(validated) > 0:
        logger.info(
            "Node 'quality_check': %d validated finding(s) is sufficient; proceeding to report.",
            len(validated),
        )
        return Command(update={"errors": errors}, goto="report")

    if retry_count >= MAX_RETRY_COUNT:
        logger.warning(
            "Node 'quality_check': insufficient validated findings and the max retry "
            "limit (%d) has been reached; proceeding to report with what is available.",
            MAX_RETRY_COUNT,
        )
        errors.append(
            f"quality_check: insufficient validated findings (0) after {retry_count} "
            f"retr{'y' if retry_count == 1 else 'ies'}; max retries reached, proceeding anyway."
        )
        return Command(update={"errors": errors}, goto="report")

    new_retry_count = retry_count + 1
    logger.warning(
        "Node 'quality_check': insufficient validated findings; retrying research "
        "(attempt %d/%d).",
        new_retry_count,
        MAX_RETRY_COUNT,
    )
    errors.append(
        f"quality_check: insufficient validated findings (0); "
        f"retrying research (attempt {new_retry_count}/{MAX_RETRY_COUNT})."
    )
    return Command(
        update={"retry_count": new_retry_count, "errors": errors}, goto="plan"
    )


# ---------------------------------------------------------------------------
# Wired nodes (Step 6B): plan -> QueryPlanner, search -> TavilySearchService
# ---------------------------------------------------------------------------
#
# These are built as small factories so a QueryPlanner/TavilySearchService
# instance (real or a test double) can be injected at graph-build time,
# rather than each node constructing its own service internally.


def _make_plan_node(query_planner: QueryPlanner):
    def plan_node(state: ResearchState) -> ResearchState:
        """Call QueryPlanner.create_plan() on the user's prompt."""
        logger.info("Node 'plan' executing: calling QueryPlanner.")
        errors = list(state.get("errors", []))

        try:
            plan = query_planner.create_plan(state["user_prompt"])
        except QueryPlannerError as exc:
            logger.error("Node 'plan' failed: %s", exc)
            errors.append(f"plan: {exc}")
            return {"errors": errors}

        return {
            "research_plan": plan,
            "search_queries": plan.search_queries,
            "errors": errors,
        }

    return plan_node


def _make_search_node(tavily_service: TavilySearchService):
    def search_node(state: ResearchState) -> ResearchState:
        """Call TavilySearchService.search() for each planned query."""
        logger.info("Node 'search' executing: calling TavilySearchService.")
        errors = list(state.get("errors", []))
        queries = state.get("search_queries") or []

        if not queries:
            logger.warning("Node 'search': no search_queries available to run.")
            errors.append("search: no search_queries available to run.")
            return {"search_results": [], "errors": errors}

        all_results: list[SearchResult] = []
        for search_query in queries:
            try:
                results = tavily_service.search(search_query.query)
            except TavilyServiceError as exc:
                logger.error(
                    "Node 'search' failed for query=%r: %s", search_query.query, exc
                )
                errors.append(f"search: query={search_query.query!r} failed ({exc})")
                continue
            all_results.extend(results)

        return {"search_results": all_results, "errors": errors}

    return search_node


def _make_summarize_node(summarizer: Summarizer):
    def summarize_node(state: ResearchState) -> ResearchState:
        """Call Summarizer.summarize() on the cleaned search_results."""
        logger.info("Node 'summarize' executing: calling Summarizer.")
        errors = list(state.get("errors", []))
        search_results = state.get("search_results") or []
        plan = state.get("research_plan")
        main_topic = plan.main_topic if plan else None
        sub_topics = plan.sub_topics if plan else None

        if not search_results:
            logger.warning("Node 'summarize': no search_results available to summarize.")
            errors.append("summarize: no search_results available to summarize.")
            return {"findings": [], "errors": errors}

        try:
            findings = summarizer.summarize(
                search_results, main_topic=main_topic, sub_topics=sub_topics
            )
        except SummarizerError as exc:
            logger.error("Node 'summarize' failed: %s", exc)
            errors.append(f"summarize: {exc}")
            return {"findings": [], "errors": errors}

        return {"findings": findings, "errors": errors}

    return summarize_node


def _make_report_node(report_generator: ReportGenerator):
    def report_node(state: ResearchState) -> ResearchState:
        """Call ReportGenerator.generate_report() on the validated_findings."""
        logger.info("Node 'report' executing: calling ReportGenerator.")
        errors = list(state.get("errors", []))
        validated_findings = state.get("validated_findings") or []
        plan = state.get("research_plan")
        main_topic = plan.main_topic if plan else None
        response_language = state.get("response_language", "English")

        if not validated_findings:
            logger.warning("Node 'report': no validated_findings available to report on.")
            errors.append("report: no validated_findings available to generate a report.")
            return {"final_report": None, "errors": errors}

        try:
            report = report_generator.generate_report(
                validated_findings,
                main_topic=main_topic,
                response_language=response_language,
            )
        except ReportGeneratorError as exc:
            logger.error("Node 'report' failed: %s", exc)
            errors.append(f"report: {exc}")
            return {"final_report": None, "errors": errors}

        return {"final_report": report, "errors": errors}

    return report_node


# ---------------------------------------------------------------------------
# Graph builder
# ---------------------------------------------------------------------------


def build_research_graph(
    query_planner: QueryPlanner | None = None,
    tavily_service: TavilySearchService | None = None,
    summarizer: Summarizer | None = None,
    report_generator: ReportGenerator | None = None,
) -> CompiledStateGraph:
    """
    Build and compile the research pipeline's StateGraph.

    Sequential structure (with a retry loop):
        START -> analyze -> plan -> search -> process -> summarize
              -> validate -> quality_check -> report -> END
                                  ^                |
                                  +---- (retry) ----+
        `quality_check` routes back to `plan` (incrementing `retry_count`)
        up to `MAX_RETRY_COUNT` times if `validated_findings` is empty,
        otherwise proceeds straight on to `report`.

    Args:
        query_planner: Optional `QueryPlanner` (or compatible test double
            exposing `.create_plan(prompt)`) used by the `plan` node.
            Defaults to a real `QueryPlanner()`.
        tavily_service: Optional `TavilySearchService` (or compatible test
            double exposing `.search(query)`) used by the `search` node.
            Defaults to a real `TavilySearchService()`.
        summarizer: Optional `Summarizer` (or compatible test double
            exposing `.summarize(search_results, main_topic, sub_topics)`)
            used by the `summarize` node. Defaults to a real `Summarizer()`.
        report_generator: Optional `ReportGenerator` (or compatible test
            double exposing `.generate_report(validated_findings, main_topic, response_language)`)
            used by the `report` node. Defaults to a real `ReportGenerator()`.

    Returns:
        A compiled LangGraph graph, ready to `.invoke(...)` with a
        `ResearchState` (e.g. from `create_initial_state`).
    """
    query_planner = query_planner or QueryPlanner()
    tavily_service = tavily_service or TavilySearchService()
    summarizer = summarizer or Summarizer()
    report_generator = report_generator or ReportGenerator()

    graph = StateGraph(ResearchState)

    graph.add_node("analyze", analyze_node)
    graph.add_node("plan", _make_plan_node(query_planner))
    graph.add_node("search", _make_search_node(tavily_service))
    graph.add_node("process", process_node)
    graph.add_node("summarize", _make_summarize_node(summarizer))
    graph.add_node("validate", validate_node)
    graph.add_node("quality_check", quality_check_node)
    graph.add_node("report", _make_report_node(report_generator))

    graph.add_edge(START, "analyze")
    graph.add_edge("analyze", "plan")
    graph.add_edge("plan", "search")
    graph.add_edge("search", "process")
    graph.add_edge("process", "summarize")
    graph.add_edge("summarize", "validate")
    graph.add_edge("validate", "quality_check")
    # No static edge from "quality_check": it routes dynamically to either
    # "plan" (retry) or "report" (proceed) via the Command it returns.
    graph.add_edge("report", END)

    return graph.compile()
